# This would set the action to run on a schedule, but for now I only want it to 
# run manually, so I'm using "on: workflow_dispatch" instead
# on:
#   schedule:
#     - cron: "0 12 * * *"

on: workflow_dispatch

jobs:
  post-to-bsky:
    runs-on: ubuntu-latest
    
    env:
      BSKY_USER: ${{ secrets.BSKY_USER }}
      BSKY_PASS: ${{ secrets.BSKY_PASS }}

    steps:
    - uses: actions/checkout@v2

    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: "renv"
        # install-r: false
        use-public-rspm: true

    - uses: r-lib/actions/setup-renv@v2

    - run: Rscript 'script.R'
